// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IconEpFold: typeof import('~icons/ep/fold')['default']
    'IconIc:baseline10k': typeof import('~icons/ic/baseline10k')['default']
    IconMaterialSymbols10k: typeof import('~icons/material-symbols/10k')['default']
    'IconRi:24HoursFill': typeof import('~icons/ri/24-hours-fill')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
